---
- name: Update apt cache
  apt:
    update_cache: yes
  become: true

- name: Install kubernetes requirements
  apt:
    name: "{{ kube_requirements }}"
    state: present
  become: true

- name: Add kubernetes gpg key
  apt_key:
    url: "{{ kube_gpg_key }}"
    state: present
  become: true

- name: Add kube repository
  apt_repository:
    repo: "{{ kube_repository }}"
    state: present
    filename: kubernetes
    update_cache: yes
  become: true

- name: Install kube packages
  apt:
    name: "{{ kube_packages }}"
    state: present
  become: true

- name: Check helm binary
  stat:
    path: /usr/bin/helm
  register: helm_bin
  become: true

- name: Warn about binary existence
  debug:
    msg: Helm binary already exists
  when: helm_bin.stat.exists

- name: Download helm setup script
  get_url:
    url: https://git.io/get_helm.sh
    dest: /opt/install-helm.sh
    mode: 0755
  become: true
  when: not helm_bin.stat.exists

- name: Install helm
  command: /opt/install-helm.sh
  become: true
  when: not helm_bin.stat.exists

- name: Install helm
  copy:
    src: /usr/local/bin/helm
    dest: /usr/bin/helm
    remote_src: true
  become: true
  when: not helm_bin.stat.exists

- name: Prevent kube packages to update
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop: "{{ kube_packages }}"
  become: true
