[prune]
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "k8s.io/client-go"
    unused-packages = false

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.3.0"

[[constraint]]
  name = "github.com/gin-contrib/logger"
  version = "v0.0.1"

[[constraint]]
  name = "github.com/rs/zerolog"
  version = "v1.14.3"

[[constraint]]
  name = "k8s.io/client-go"
  version = "v11.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/zsais/go-gin-prometheus"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.14.0"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.14.0"
