replicaCount: 1

image:
  repository: tioxy/scheduler
  tag: latest
  pullPolicy: Always
  port: 8080
  debug: true

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: scheduler.tioxy.com
      paths:
        - "/"

resources: {}

rbac:
  enabled: true
